name: translation2json
description: Generate localization json file by excel file
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  args: ^2.2.0
  excel: ^2.0.0-null-safety-3

dev_dependencies:
  test: ^1.15.7
